# -*- coding: utf-8 -*-
"""Untitled120.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-sfLuCD0wrqE4ZD90zyVhpX5ekn4crI
"""

!pip install xgboost joblib

import os
import json
import joblib
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import (r2_score,mean_absolute_error)

from xgboost import XGBRegressor

df = pd.read_csv('/content/farmer_scoring_sample_yogyank_round1_final.csv')

df.head()

df.shape

df.isnull().sum()

""" # SAFE FEATURES"""

features = [
        "land_area_acres",
        "crop_type",
        "pm_kisan_status",
        "historical_repayment_score"
    ]

target = "target_entitlement_score"

"""   # BECAUSE IT USES FUTURE INFORMATION."""

X = df[features].copy()
y = df[target]

# COLUMN TYPES
categorical_cols = [
        "crop_type",
        "pm_kisan_status"
    ]

numeric_cols = [
        "land_area_acres",
        "historical_repayment_score"
    ]

# PREPROCESSOR
preprocessor = ColumnTransformer(
        transformers=[

            (
                "cat",
                OneHotEncoder(
                    handle_unknown="ignore"
                ),
                categorical_cols
            ),

            (
                "num",
                SimpleImputer(
                    strategy="median"
                ),
                numeric_cols
            )
        ]
    )

# PIPELINE

pipeline = Pipeline([

        (
            "preprocessor",
            preprocessor
        ),

        (
            "model",

            XGBRegressor(

                n_estimators=100,
                max_depth=4,
                learning_rate=0.05,
                random_state=42,
                n_jobs=1,
                tree_method="hist"
            )
        )
    ])

X_train, X_test, y_train, y_test = train_test_split(

        X,
        y,

        test_size=0.2,

        shuffle=False
    )

print("\nTraining Size:", X_train.shape)
print("Testing Size:", X_test.shape)

"""Train Model"""

print("\nTraining Model...")

pipeline.fit(
        X_train,
        y_train
    )
print("Training Completed")

""" PREDICT"""

preds = pipeline.predict(X_test)
preds

"""  # METRICS"""

r2 = r2_score(y_test, preds)

mae = mean_absolute_error(y_test, preds)

print("\n============================")
print("MODEL PERFORMANCE")
print("============================")

print(f"R2 Score : {r2:.4f}")

print(f"MAE      : {mae:.2f}")

""" # ARTIFACTS"""

os.makedirs(
        "artifacts",
        exist_ok=True
    )

""" # SAVE PIPELINE"""

joblib.dump(
        pipeline,
        "artifacts/yogyank_pipeline.pkl"
    )

print("\nPipeline Saved")

# SAVE SCHEMA
schema = {

        "features": features,

        "target": target
    }

with open(
        "artifacts/schema.json",
        "w"
    ) as f:

        json.dump(
            schema,
            f,
            indent=2
        )

# SAVE VERSION
metadata = {

        "model_version": "1.0.0",

        "algorithm": "XGBoost",

        "validation_strategy":
        "holdout_without_shuffle",

        "removed_leakage_column":
        "defaulted_in_next_12_months"
    }

with open(
        "artifacts/version.json",
        "w"
    ) as f:

        json.dump(
            metadata,
            f,
            indent=2
        )


print("Metadata Saved")

# REASON CODES
feature_names = pipeline.named_steps[
        "preprocessor"
    ].get_feature_names_out()

importances = pipeline.named_steps[
        "model"
    ].feature_importances_


importance_df = pd.DataFrame({

        "feature": feature_names,

        "importance": importances
    })

top_3 = importance_df.sort_values(

        by="importance",

        ascending=False

    ).head(3)

print("\n============================")
print("TOP 3 REASON CODES")
print("============================")

print(top_3)


print("\nAll Artifacts Saved Successfully")

# MAIN
if __name__ == "__main__":
  train_model()